name: 'Setup Anchor'
description: 'Install Anchor, Solana CLI tools, and Node.js.'
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: 'Version of node.js to use'
    required: false
    default: '20.18.0' # ensure this matches our current actions
  solana-cli-version:
    description: 'Version of Solana CLI to use'
    required: false
    default: '2.2.15' # ensure this matches our current actions
  anchor-version:
    description: 'Version of Anchor to use'
    required: false
    default: '0.31.1' # ensure this matches our current actions
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache Solana CLI tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-cli-${{ runner.os }}-build-${{ inputs.solana-cli-version }}
    - name: Install Solana CLI tools
      # Use the old solana.com release if the version starts with 1, Anza otherwise
      # swap this to other actions 
      run: |
        if [[ "${{ inputs.solana-cli-version }}" == 1* ]]; then
          cd $HOME
          wget https://github.com/solana-labs/solana/releases/download/v${{ inputs.solana-cli-version }}/solana-release-x86_64-unknown-linux-gnu.tar.bz2
          tar jxf solana-release-x86_64-unknown-linux-gnu.tar.bz2
          echo "$HOME/solana-release/bin" >> $GITHUB_PATH
        else
          sh -c "$(curl -sSfL https://release.anza.xyz/v${{ inputs.solana-cli-version }}/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        fi
      shell: bash
    - name: Update PATH
      run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH 
      shell: bash
    - name: Install Anchor
      run: cargo install --git https://github.com/coral-xyz/anchor --tag v${{ inputs.anchor-version }} anchor-cli --locked
      shell: bash